(function() {
  var $, api_base, authorize, load_comments, load_footer, load_reply, marked, petal, post_reply, warning_hide, warning_show;

  $ = jQuery;

  $.support.cors = true;

  api_base = "https://api.github.com/repos/";

  marked = require("marked");

  petal = {
    repo: "user/repo",
    issue_id: 1,
    init: function(repo, issue_id) {
      this.repo = repo;
      this.issue_id = issue_id;
      this.api_url = api_base + this.repo + "/issues/" + this.issue_id + "/comments";
      $(".petal").append("<div class=\"comments\"></div><div class=\"reply\" ></div><div class=\"footer\"></div>");
      load_reply();
      load_footer();
      return load_comments();
    }
  };

  $.petal = petal;

  load_footer = function() {
    return $(".petal .footer").html("By <a href=\"https://github.com/hit9/petal\">petal</a>");
  };

  load_comments = function() {
    return $.getJSON(petal.api_url + "?callback=?", function(response) {
      var com, comments, _i, _len, _results;
      comments = response.data;
      $(".petal .comments").append("<ul></ul>");
      _results = [];
      for (_i = 0, _len = comments.length; _i < _len; _i++) {
        com = comments[_i];
        _results.push($(".petal .comments ul").append("      <li>        <div class=\"user\">                    <img src=\"https://secure.gravatar.com/avatar/" + com.user.gravatar_id + "?s=50\" />          <a class=\"username\" href=\"https://github.com/" + com.user.login + "\" >" + com.user.login + "</a>        </div>        <div class=\"content\">          <div class=\"body\"" + marked(com.body) + "</div>        </div>      </li>      "));
      }
      return _results;
    });
  };

  load_reply = function() {
    $(".petal .reply").append("    <p class=\"note\">Require Github account.</p>    <p class=\"warning\"></p>    <textarea id=\"petal-textarea\"></textarea>    <p class=\"note\" >Press Ctrl+Enter to post your comment.</p>  ");
    return $("#petal-textarea").keydown(function(e) {
      var content;
      if (e.keyCode === 10 || e.keyCode === 13 && e.ctrlKey) {
        content = $("#petal-textarea").val();
        if (content) {
          return post_reply(content);
        } else {
          return warning_show("Comment field was blank");
        }
      }
    });
  };

  post_reply = function(content) {
    var storage;
    storage = window.localStorage;
    if (storage.getItem("petal_token") === null) {
      return authorize();
    }
  };

  authorize = function() {};

  warning_show = function(msg) {
    $(".warning").show();
    return $(".warning").text(msg);
  };

  warning_hide = function() {
    return $(".warning").hide();
  };

}).call(this);

// Generated by CoffeeScript 1.5.0-pre
