(function() {
  var $, api_base, load_comments, marked, petal;

  $ = jQuery;

  $.support.cors = true;

  api_base = "https://api.github.com/repos/";

  marked = require("marked");

  petal = {
    repo: "user/repo",
    issue_id: 1,
    init: function(repo, issue_id) {
      this.repo = repo;
      this.issue_id = issue_id;
      this.api_url = api_base + this.repo + "/issues/" + this.issue_id + "/comments";
      return load_comments();
    }
  };

  $.petal = petal;

  load_comments = function() {
    return $.getJSON(petal.api_url + "?callback=?", function(response) {
      var com, comments, _i, _len, _results;
      comments = response.data;
      $(".petal").append("<ul></ul>");
      _results = [];
      for (_i = 0, _len = comments.length; _i < _len; _i++) {
        com = comments[_i];
        _results.push($(".petal ul").append("      <li>        <div class=\"user\">                    <img src=\"https://secure.gravatar.com/avatar/" + com.user.gravatar_id + "?s=50\" />          <a class=\"username\" href=\"https://github.com/" + com.user.login + "\" >" + com.user.login + "</a>        </div>        <div class=\"content\">          <div class=\"body\"" + marked(com.body) + "</div>        </div>      </li>      "));
      }
      return _results;
    });
  };

}).call(this);

// Generated by CoffeeScript 1.5.0-pre
